name: Build SynchronousAudioRouter
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: "[17.0,18.0)"
          msbuild-architecture: x64
      - name: Build 32
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild SynchronousAudioRouter.sln /t:Build /p:Configuration=Release /p:Platform=x86 /m /verbosity:minimal
      - name: Build 64
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild SynchronousAudioRouter.sln /t:Build /p:Configuration=Release /p:Platform=x64 /m /verbosity:minimal
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SynchronousAudioRouter
          path: SarInstaller/bin/x64/Release/SynchronousAudioRouter.msi
